
package TurboPac;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ITurboPacWs", targetNamespace = "http://turbopac.mx/TurboPac")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ITurboPacWs {


    /**
     * 
     * @param password
     * @param comprobante
     * @param userName
     * @return
     *     returns mypackage.RespuestaTimbrado
     */
    @WebMethod(operationName = "TimbraCfdi", action = "http://turbopac.mx/TurboPac/ITurboPacWs/TimbraCfdi")
    @WebResult(name = "TimbraCfdiResult", targetNamespace = "http://turbopac.mx/TurboPac")
    @RequestWrapper(localName = "TimbraCfdi", targetNamespace = "http://turbopac.mx/TurboPac", className = "mypackage.TimbraCfdi")
    @ResponseWrapper(localName = "TimbraCfdiResponse", targetNamespace = "http://turbopac.mx/TurboPac", className = "mypackage.TimbraCfdiResponse")
    public RespuestaTimbrado timbraCfdi(
        @WebParam(name = "userName", targetNamespace = "http://turbopac.mx/TurboPac")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://turbopac.mx/TurboPac")
        String password,
        @WebParam(name = "comprobante", targetNamespace = "http://turbopac.mx/TurboPac")
        String comprobante);

    /**
     * 
     * @param password
     * @param comprobante
     * @param userName
     * @return
     *     returns mypackage.RespuestaTimbrado
     */
    @WebMethod(operationName = "TimbraCfdi33", action = "http://turbopac.mx/TurboPac/ITurboPacWs/TimbraCfdi33")
    @WebResult(name = "TimbraCfdi33Result", targetNamespace = "http://turbopac.mx/TurboPac")
    @RequestWrapper(localName = "TimbraCfdi33", targetNamespace = "http://turbopac.mx/TurboPac", className = "mypackage.TimbraCfdi33")
    @ResponseWrapper(localName = "TimbraCfdi33Response", targetNamespace = "http://turbopac.mx/TurboPac", className = "mypackage.TimbraCfdi33Response")
    public RespuestaTimbrado timbraCfdi33(
        @WebParam(name = "userName", targetNamespace = "http://turbopac.mx/TurboPac")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://turbopac.mx/TurboPac")
        String password,
        @WebParam(name = "comprobante", targetNamespace = "http://turbopac.mx/TurboPac")
        String comprobante);

    /**
     * 
     * @param password
     * @param userName
     * @param url
     * @return
     *     returns mypackage.RespuestaTimbrado
     */
    @WebMethod(operationName = "TimbraURLCfdi33", action = "http://turbopac.mx/TurboPac/ITurboPacWs/TimbraURLCfdi33")
    @WebResult(name = "TimbraURLCfdi33Result", targetNamespace = "http://turbopac.mx/TurboPac")
    @RequestWrapper(localName = "TimbraURLCfdi33", targetNamespace = "http://turbopac.mx/TurboPac", className = "mypackage.TimbraURLCfdi33")
    @ResponseWrapper(localName = "TimbraURLCfdi33Response", targetNamespace = "http://turbopac.mx/TurboPac", className = "mypackage.TimbraURLCfdi33Response")
    public RespuestaTimbrado timbraURLCfdi33(
        @WebParam(name = "userName", targetNamespace = "http://turbopac.mx/TurboPac")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://turbopac.mx/TurboPac")
        String password,
        @WebParam(name = "url", targetNamespace = "http://turbopac.mx/TurboPac")
        String url);

    /**
     * 
     * @param password
     * @param comprobante
     * @param userName
     * @return
     *     returns mypackage.RespuestaTimbrado
     */
    @WebMethod(operationName = "TimbraCfdi40", action = "http://turbopac.mx/TurboPac/ITurboPacWs/TimbraCfdi40")
    @WebResult(name = "TimbraCfdi40Result", targetNamespace = "http://turbopac.mx/TurboPac")
    @RequestWrapper(localName = "TimbraCfdi40", targetNamespace = "http://turbopac.mx/TurboPac", className = "mypackage.TimbraCfdi40")
    @ResponseWrapper(localName = "TimbraCfdi40Response", targetNamespace = "http://turbopac.mx/TurboPac", className = "mypackage.TimbraCfdi40Response")
    public RespuestaTimbrado timbraCfdi40(
        @WebParam(name = "userName", targetNamespace = "http://turbopac.mx/TurboPac")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://turbopac.mx/TurboPac")
        String password,
        @WebParam(name = "comprobante", targetNamespace = "http://turbopac.mx/TurboPac")
        String comprobante);

    /**
     * 
     * @param password
     * @param userName
     * @param url
     * @return
     *     returns mypackage.RespuestaTimbrado
     */
    @WebMethod(operationName = "TimbraURLCfdi40", action = "http://turbopac.mx/TurboPac/ITurboPacWs/TimbraURLCfdi40")
    @WebResult(name = "TimbraURLCfdi40Result", targetNamespace = "http://turbopac.mx/TurboPac")
    @RequestWrapper(localName = "TimbraURLCfdi40", targetNamespace = "http://turbopac.mx/TurboPac", className = "mypackage.TimbraURLCfdi40")
    @ResponseWrapper(localName = "TimbraURLCfdi40Response", targetNamespace = "http://turbopac.mx/TurboPac", className = "mypackage.TimbraURLCfdi40Response")
    public RespuestaTimbrado timbraURLCfdi40(
        @WebParam(name = "userName", targetNamespace = "http://turbopac.mx/TurboPac")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://turbopac.mx/TurboPac")
        String password,
        @WebParam(name = "url", targetNamespace = "http://turbopac.mx/TurboPac")
        String url);

    /**
     * 
     * @param password
     * @param userName
     * @param requestCancelacion
     * @return
     *     returns mypackage.RespuestaCancelacion
     */
    @WebMethod(operationName = "CancelaCfdi", action = "http://turbopac.mx/TurboPac/ITurboPacWs/CancelaCfdi")
    @WebResult(name = "CancelaCfdiResult", targetNamespace = "http://turbopac.mx/TurboPac")
    @RequestWrapper(localName = "CancelaCfdi", targetNamespace = "http://turbopac.mx/TurboPac", className = "mypackage.CancelaCfdi")
    @ResponseWrapper(localName = "CancelaCfdiResponse", targetNamespace = "http://turbopac.mx/TurboPac", className = "mypackage.CancelaCfdiResponse")
    public RespuestaCancelacion cancelaCfdi(
        @WebParam(name = "userName", targetNamespace = "http://turbopac.mx/TurboPac")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://turbopac.mx/TurboPac")
        String password,
        @WebParam(name = "requestCancelacion", targetNamespace = "http://turbopac.mx/TurboPac")
        String requestCancelacion);

    /**
     * 
     * @param password
     * @param comprobante
     * @param userName
     * @return
     *     returns mypackage.RespuestaTimbrado
     */
    @WebMethod(operationName = "TimbraRetencion", action = "http://turbopac.mx/TurboPac/ITurboPacWs/TimbraRetencion")
    @WebResult(name = "TimbraRetencionResult", targetNamespace = "http://turbopac.mx/TurboPac")
    @RequestWrapper(localName = "TimbraRetencion", targetNamespace = "http://turbopac.mx/TurboPac", className = "mypackage.TimbraRetencion")
    @ResponseWrapper(localName = "TimbraRetencionResponse", targetNamespace = "http://turbopac.mx/TurboPac", className = "mypackage.TimbraRetencionResponse")
    public RespuestaTimbrado timbraRetencion(
        @WebParam(name = "userName", targetNamespace = "http://turbopac.mx/TurboPac")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://turbopac.mx/TurboPac")
        String password,
        @WebParam(name = "comprobante", targetNamespace = "http://turbopac.mx/TurboPac")
        String comprobante);

    /**
     * 
     * @param password
     * @param userName
     * @param requestCancelacion
     * @return
     *     returns mypackage.RespuestaCancelacion
     */
    @WebMethod(operationName = "CancelaRetencion", action = "http://turbopac.mx/TurboPac/ITurboPacWs/CancelaRetencion")
    @WebResult(name = "CancelaRetencionResult", targetNamespace = "http://turbopac.mx/TurboPac")
    @RequestWrapper(localName = "CancelaRetencion", targetNamespace = "http://turbopac.mx/TurboPac", className = "mypackage.CancelaRetencion")
    @ResponseWrapper(localName = "CancelaRetencionResponse", targetNamespace = "http://turbopac.mx/TurboPac", className = "mypackage.CancelaRetencionResponse")
    public RespuestaCancelacion cancelaRetencion(
        @WebParam(name = "userName", targetNamespace = "http://turbopac.mx/TurboPac")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://turbopac.mx/TurboPac")
        String password,
        @WebParam(name = "requestCancelacion", targetNamespace = "http://turbopac.mx/TurboPac")
        String requestCancelacion);

    /**
     * 
     * @param password
     * @param userName
     * @param uuid
     * @return
     *     returns mypackage.ResultadoConsulta
     */
    @WebMethod(operationName = "ObtenerStatusUuid", action = "http://turbopac.mx/TurboPac/ITurboPacWs/ObtenerStatusUuid")
    @WebResult(name = "ObtenerStatusUuidResult", targetNamespace = "http://turbopac.mx/TurboPac")
    @RequestWrapper(localName = "ObtenerStatusUuid", targetNamespace = "http://turbopac.mx/TurboPac", className = "mypackage.ObtenerStatusUuid")
    @ResponseWrapper(localName = "ObtenerStatusUuidResponse", targetNamespace = "http://turbopac.mx/TurboPac", className = "mypackage.ObtenerStatusUuidResponse")
    public ResultadoConsulta obtenerStatusUuid(
        @WebParam(name = "userName", targetNamespace = "http://turbopac.mx/TurboPac")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://turbopac.mx/TurboPac")
        String password,
        @WebParam(name = "uuid", targetNamespace = "http://turbopac.mx/TurboPac")
        String uuid);

}
