
package TurboPac;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TurboPacWs", targetNamespace = "http://turbopac.mx/TurboPac", wsdlLocation = "http://sidetecdsl.selfip.com:8081/TimbradoTp/TurboPacWs.svc?singleWsdl")
public class TurboPacWs
    extends Service
{

    private final static URL TURBOPACWS_WSDL_LOCATION;
    private final static WebServiceException TURBOPACWS_EXCEPTION;
    private final static QName TURBOPACWS_QNAME = new QName("http://turbopac.mx/TurboPac", "TurboPacWs");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://sidetecdsl.selfip.com:8081/TimbradoTp/TurboPacWs.svc?singleWsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TURBOPACWS_WSDL_LOCATION = url;
        TURBOPACWS_EXCEPTION = e;
    }

    public TurboPacWs() {
        super(__getWsdlLocation(), TURBOPACWS_QNAME);
    }

    public TurboPacWs(WebServiceFeature... features) {
        super(__getWsdlLocation(), TURBOPACWS_QNAME, features);
    }

    public TurboPacWs(URL wsdlLocation) {
        super(wsdlLocation, TURBOPACWS_QNAME);
    }

    public TurboPacWs(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TURBOPACWS_QNAME, features);
    }

    public TurboPacWs(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TurboPacWs(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ITurboPacWs
     */
    @WebEndpoint(name = "BasicHttpBinding_ITurboPacWs")
    public ITurboPacWs getBasicHttpBindingITurboPacWs() {
        return super.getPort(new QName("http://turbopac.mx/TurboPac", "BasicHttpBinding_ITurboPacWs"), ITurboPacWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ITurboPacWs
     */
    @WebEndpoint(name = "BasicHttpBinding_ITurboPacWs")
    public ITurboPacWs getBasicHttpBindingITurboPacWs(WebServiceFeature... features) {
        return super.getPort(new QName("http://turbopac.mx/TurboPac", "BasicHttpBinding_ITurboPacWs"), ITurboPacWs.class, features);
    }

    /**
     * 
     * @return
     *     returns ITurboPacWs
     */
    @WebEndpoint(name = "BasicHttpsBinding_ITurboPacWs")
    public ITurboPacWs getBasicHttpsBindingITurboPacWs() {
        return super.getPort(new QName("http://turbopac.mx/TurboPac", "BasicHttpsBinding_ITurboPacWs"), ITurboPacWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ITurboPacWs
     */
    @WebEndpoint(name = "BasicHttpsBinding_ITurboPacWs")
    public ITurboPacWs getBasicHttpsBindingITurboPacWs(WebServiceFeature... features) {
        return super.getPort(new QName("http://turbopac.mx/TurboPac", "BasicHttpsBinding_ITurboPacWs"), ITurboPacWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TURBOPACWS_EXCEPTION!= null) {
            throw TURBOPACWS_EXCEPTION;
        }
        return TURBOPACWS_WSDL_LOCATION;
    }

}
